import type { PatternGeometry } from "@/types";

export interface SvgExportOptions {
  width: number;
  height: number;
  backgroundColor: string;
  pointRadius: number;
  strokeWidth: number;
  maxNodes: number;
  simplification: number;
  includeBackground: boolean;
  presetName: string;
}

export function exportGeometryToSvg(geometry: PatternGeometry, options: SvgExportOptions): string {
  const maxNodes = Math.max(1, Math.floor(options.maxNodes));
  const simplification = clamp(options.simplification, 0, 1);
  const targetPointNodes = Math.max(1, Math.floor(maxNodes * (0.45 - simplification * 0.25)));
  const targetPathNodes = Math.max(1, Math.floor(maxNodes * (0.2 - simplification * 0.1)));
  const targetPathPoints = Math.max(2, Math.floor(maxNodes * (0.55 - simplification * 0.35)));
  const sampledPaths = sampleArray(
    geometry.paths,
    Math.max(1, Math.ceil(geometry.paths.length / targetPathNodes))
  );
  const sampledPoints = sampleArray(
    geometry.points,
    Math.max(1, Math.ceil(geometry.points.length / targetPointNodes))
  );

  const background = options.includeBackground
    ? `<rect width="100%" height="100%" fill="${escapeXml(options.backgroundColor)}" />`
    : "";

  const pointNodes = sampledPoints
    .map((point) => {
      return `<circle cx="${round(point.x)}" cy="${round(point.y)}" r="${round(options.pointRadius)}" fill="currentColor" />`;
    })
    .join("\n");

  const pathNodes = sampledPaths
    .map((path) => {
      const pathBudget = Math.max(2, Math.floor(targetPathPoints / Math.max(1, sampledPaths.length)));
      const sampledPath = sampleArray(path.points, Math.max(1, Math.ceil(path.points.length / pathBudget)));
      if (sampledPath.length < 2) return "";
      const d = sampledPath
        .map((point, index) => `${index === 0 ? "M" : "L"} ${round(point.x)} ${round(point.y)}`)
        .join(" ");

      return `<path d="${d}${path.closed ? " Z" : ""}" fill="none" stroke="currentColor" stroke-width="${round(options.strokeWidth)}" />`;
    })
    .filter(Boolean)
    .join("\n");

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${options.width}" height="${options.height}" viewBox="0 0 ${options.width} ${options.height}" color="#7dd3fc">`,
    `<title>SonicField Studio Export</title>`,
    `<desc>Generated by SonicField Studio. Preset: ${escapeXml(options.presetName)}. Dimensions: ${options.width}x${options.height}. Geometry nodes: ${geometry.meta.estimatedSvgNodeCount}. Simplification: ${round(simplification)}.</desc>`,
    background,
    `<g id="paths">`,
    pathNodes,
    `</g>`,
    `<g id="points">`,
    pointNodes,
    `</g>`,
    `</svg>`
  ].join("\n");
}

function sampleArray<T>(items: T[], step: number): T[] {
  if (step <= 1) return items;
  return items.filter((_, index) => index % step === 0);
}

function round(value: number): number {
  return Math.round(value * 1000) / 1000;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function escapeXml(value: string): string {
  return value.replace(/[<>&'"]/g, (char) => {
    switch (char) {
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case "&":
        return "&amp;";
      case "'":
        return "&apos;";
      case "\"":
        return "&quot;";
      default:
        return char;
    }
  });
}
